name: Main PR TEST

on:
  pull_request:
    branches:
      - "main"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      REDIS_PORT: ${{secrets.REDIS_PORT}}
      SSE_EMITTER_TIMEOUT: ${{secrets.SSE_EMITTER_TIMEOUT}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Debug JWT Secret Key
        run: |
          echo "JWT_SECRET_KEY is set: ${#JWT_SECRET_KEY}"
          echo "AWS_SECRET_KEY is set: ${#AWS_SECRET_KEY}"
          echo "AWS_ACCESS_KEY is set: ${#AWS_ACCESS_KEY}"
      - name: Run tests
        run: |
          cd floe
          ./gradlew clean
          ./gradlew test -Dspring.profiles.active=test -i