name: Main PR TEST

on:
  pull_request:
    branches:
      - "feat/#33"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add JWT Secret Key to Properties
        run: |
          cd floe
          echo "jwt.secretKey=${{ secrets.JWT_SECRET_KEY }}" >> ./src/test/resources/application-test.properties
          cat src/test/resources/application-test.properties

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run tests
        run: |
          cd floe
          ./gradlew clean
          ./gradlew test -Dspring.profiles.active=test
